### ISSUE TITLE
[desktop-kit] app-backup/borgbackup doesn't compile

### ISSUE THREAD

**Issue by geaaru** [macaroni-os/mark-issues#101]
```

Calculating dependencies  .. .... . ....... done!
[ebuild  N     ] app-backup/borgbackup-1.4.0::desktop-kit  USE="-libressl" PYTHON_TARGETS="python3_9 -python3_10 -python3_7 -python3_8" 3,710 KiB
[ebuild  N     ]  dev-python/llfuse-1.5.0::python-modules-kit  USE="-doc -examples -test" PYTHON_TARGETS="python3_9 -python3_10 -python3_7 -python3_8" 849 KiB

Total: 2 packages (2 new), Size of downloads: 4,559 KiB
[91m
!!! The following installed packages are masked:
[0m[91m- app-arch/rar-5.7.1_p20190427::core-kit (masked by: RAR license(s))
[0m[91mA copy of the 'RAR' license is located at '/var/git/meta-repo/kits/core-kit/licenses/RAR'.

[0m[91m- app-emulation/virtualbox-bin-7.0.20.163906::core-kit (masked by: PUEL license(s))
[0m[91mA copy of the 'PUEL' license is located at '/var/git/meta-repo/kits/core-kit/licenses/PUEL'.

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.

[0m>>> Verifying ebuild manifests
>>> Jobs: 0 of 1 complete, 1 running                Load avg: 5.63, 6.75, 6.97
>>> Emerging (1 of 1) app-backup/borgbackup-1.4.0::desktop-kit
>>> Jobs: 0 of 1 complete, 1 running                Load avg: 5.63, 6.75, 6.97
>>> Failed to emerge app-backup/borgbackup-1.4.0, Log file:
>>> Jobs: 0 of 1 complete, 1 running                Load avg: 5.47, 6.68, 6.94
>>>  '/var/tmp/portage/app-backup/borgbackup-1.4.0/temp/build.log'
>>> Jobs: 0 of 1 complete, 1 running                Load avg: 5.47, 6.68, 6.94
>>> Jobs: 0 of 1 complete, 1 running, 1 failed      Load avg: 5.47, 6.68, 6.94
>>> Jobs: 0 of 1 complete, 1 failed                 Load avg: 5.47, 6.68, 6.94

 * Package:    app-backup/borgbackup-1.4.0
 * Repository: desktop-kit
 * USE:        amd64 elibc_glibc kernel_linux python_targets_python3_9 userland_GNU
 * FEATURES:   preserve-libs userpriv
>>> Unpacking source...
>>> Unpacking borgbackup-1.4.0.tar.gz to /var/tmp/portage/app-backup/borgbackup-1.4.0/work
>>> Source unpacked in /var/tmp/portage/app-backup/borgbackup-1.4.0/work
>>> Preparing source in /var/tmp/portage/app-backup/borgbackup-1.4.0/work/borgbackup-1.4.0 ...
 * Build system packages:
 *   dev-python/setuptools         : 70.3.0
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/app-backup/borgbackup-1.4.0/work/borgbackup-1.4.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/app-backup/borgbackup-1.4.0/work/borgbackup-1.4.0 ...
 * python3_9: running distutils-r1_run_phase distutils-r1_python_compile
python3.9 setup.py build -j 8
/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py:55: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
Warning: can not import pkgconfig python package.
Detected and preferring libcrypto [via BORG_OPENSSL_PREFIX]
Traceback (most recent call last):
  File "/var/tmp/portage/app-backup/borgbackup-1.4.0/work/borgbackup-1.4.0/setup.py", line 145, in <module>
    lib_ext_kwargs(pc, "BORG_LIBLZ4_PREFIX", "lz4", "liblz4", ">= 1.7.0"),
  File "/var/tmp/portage/app-backup/borgbackup-1.4.0/work/borgbackup-1.4.0/setup.py", line 125, in lib_ext_kwargs
    raise Exception(
Exception: Could not find lz4 lib/headers, please set BORG_LIBLZ4_PREFIX or ensure liblz4.pc is in PKG_CONFIG_PATH.
 * ERROR: app-backup/borgbackup-1.4.0::desktop-kit failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_compile
 *   environment, line 3580:  Called distutils-r1_src_compile
 *   environment, line 1602:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line  708:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 3176:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2650:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2648:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 1094:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line 1584:  Called distutils-r1_python_compile
 *   environment, line 1391:  Called esetup.py 'build' '-j' '8'
 *   environment, line 2185:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}";
 ```
 
 It seems needs liblz4 >= 1.7.0 but we have 1.9.3. 
 
 ```
 $ anise q files lz4 | grep liblz4
/usr/lib64/liblz4.so
/usr/lib64/liblz4.so.1
/usr/lib64/liblz4.so.1.9.3
/usr/lib64/pkgconfig/liblz4.pc
```

We need to study the issue.
Any help is welcome

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
