### ISSUE TITLE
[python-modules-kit] `dev-python/aiofiles-24.1.0` doesn't emerge

### ISSUE THREAD

**Issue by geaaru** [macaroni-os/mark-issues#105]
```
>>> Emerging (13 of 36) dev-python/aiofiles-24.1.0::python-modules-kit
 * aiofiles-24.1.0.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                                                                                         [ ok ]
>>> Unpacking source...
>>> Unpacking aiofiles-24.1.0.tar.gz to /var/tmp/portage/dev-python/aiofiles-24.1.0/work
>>> Source unpacked in /var/tmp/portage/dev-python/aiofiles-24.1.0/work
>>> Preparing source in /var/tmp/portage/dev-python/aiofiles-24.1.0/work/aiofiles-24.1.0 ...
 * Build system packages:
 *   dev-python/setuptools         : 65.3.0
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/aiofiles-24.1.0/work/aiofiles-24.1.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/aiofiles-24.1.0/work/aiofiles-24.1.0 ...
 * python3_9: running distutils-r1_run_phase distutils-r1_python_compile
python3.9 setup.py build -j 8
configuration error: `project.classifiers[8]` must be trove-classifier
DESCRIPTION:
    `PyPI classifier <https://pypi.org/classifiers/>`_.

GIVEN VALUE:
    "Programming Language :: Python :: 3.13"

OFFENDING RULE: 'format'

DEFINITION:
    {
        "type": "string",
        "format": "trove-classifier"
    }
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/aiofiles-24.1.0/work/aiofiles-24.1.0/setup.py", line 4, in <module>
    setuptools.setup()
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 868, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "/usr/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 62, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
  File "/usr/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 126, in read_configuration
    validate(subset, filepath)
  File "/usr/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 51, in validate
    raise ValueError(f"{error}\n{summary}") from None
ValueError: invalid pyproject.toml config: `project.classifiers[8]`.
configuration error: `project.classifiers[8]` must be trove-classifier
```

**Comment by geaaru** [comment]
This issue is related to a wrong migration of the rootfs to Macaroni binary package. Using mark-testing branch and upgrading to `setuptools_scm-8` all works fine.
