### ISSUE TITLE
[regen] sci-mathematics/rstudio-bin fails tree regen

### ISSUE THREAD

**Issue by org-tekeli-borisp** [macaroni-os/mark-issues#126]
````INFO     Created: sci-geosciences/qgis/qgis-3.8.3.ebuild                        
ERROR    expected string or bytes-like object                                   
         Traceback (most recent call last):                                     
           File                                                                 
         "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/autogen.py",  
         line 436, in gen_wrapper                                               
             await generate(AutoHub(autogen_id, pkgtools), **pkginfo)           
           File                                                                 
         "/home/tree/repo_tmp/source-trees/kit-fixups/science-kit/curated/sci-ma
         thematics/rstudio-bin/autogen.py", line 18, in generate                
             version =                                                          
         re.search(r"rstudio-.*-amd64",best_archive).group(0)[8:-6]             
           File "/usr/lib/python3.9/re.py", line 201, in search                 
             return _compile(pattern, flags).search(string)                     
         TypeError: expected string or bytes-like object                        
INFO     Created: sci-libs/colpack/colpack-1.0.10.ebuild                        
INFO     Created: sci-libs/libctl/libctl-4.5.1.ebuild                           
INFO     Created: sci-libs/hdf/hdf-4.3.0.ebuild                                 
INFO     Created: sci-libs/proj-data/proj-data-1.19.0.ebuild                    
INFO     Created: sci-libs/libgeotiff/libgeotiff-1.7.3.ebuild                   
INFO     Created: sci-mathematics/cgal/cgal-5.6.1.ebuild                        
INFO     Created: sci-libs/proj/proj-9.5.0.ebuild                               
INFO     Created: sci-mathematics/sfcgal/sfcgal-1.5.2.ebuild                    
INFO     Created: sci-libs/gdal/gdal-3.9.2.ebuild                               
ERROR    Autogen failed (count: 1). [<Task finished name='Task-43'              
         coro=<execute_generator.<locals>.generator_thread_task.<locals>.gen_wra
         pper() done, defined at                                                
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/autogen.py:367>
         exception=TypeError('expected string or bytes-like object')>]          
ERROR    Errors were encountered when processing the following autogens:        
ERROR     *                                                                     
         /home/tree/repo_tmp/source-trees/kit-fixups/science-kit/curated/sci-mat
         hematics/rstudio-bin/autogen.py (sci-mathematics/rstudio-bin)          
ERROR    End of report.                                                         
[?25h
ERROR    Command failure from merge-kits: cd                                    
         /home/tree/repo_tmp/source-trees/kit-fixups/science-kit/curated && doit
         --fast --release next --fastpull_scope=local --moonbeam --prod         
CRITICAL Step Autogen failed with Exception: failed autogen in                  
         /home/tree/repo_tmp/source-trees/kit-fixups -- offset                  
         science-kit/curated.                                                   
ERROR    Kit job failure:                                                       
         Traceback (most recent call last):                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 678,  
         in run                                                                 
             await method()                                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 470,  
         in generate                                                            
             await self.generate_autogenerated()                                
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 417,  
         in generate_autogenerated                                              
             await self.run(self.autogen_and_copy_from_kit_fixups())            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 159,  
         in run                                                                 
             raise e                                                            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 156,  
         in run                                                                 
             await step.run(self)                                               
           File "/usr/lib/python3.9/site-packages/metatools/steps.py", line 415,
         in run                                                                 
             await self.srctree.autogen(src_offset=self.ebuildloc,              
         scope=self.scope)                                                      
           File "/usr/lib/python3.9/site-packages/metatools/tree.py", line 88,  
         in autogen                                                             
             raise GitTreeError(f"failed autogen in {self.root} -- offset       
         {src_offset}.")                                                        
         metatools.tree.GitTreeError: failed autogen in                         
         /home/tree/repo_tmp/source-trees/kit-fixups -- offset                  
         science-kit/curated.                                                   
[?25h`````

**Comment by org-tekeli-borisp** [comment]
With the following patch
[sci-mathematics_rstudio-bin.patch.txt](https://github.com/user-attachments/files/17138058/sci-mathematics_rstudio-bin.patch.txt)
I'm able to emerge sci-mathematics/rstudio-bin
![image](https://github.com/user-attachments/assets/20988a3f-41be-4ac8-82b6-d03a86f5ee3b)
But I'm getting QA Notice
![image](https://github.com/user-attachments/assets/d2a428ef-641b-4b9e-8fc1-365ddb8321ee)
and an error message if I start the software
![image](https://github.com/user-attachments/assets/e0c996e1-7317-4e16-81b4-cbea590508ab)

@geaaru  Seems like https://github.com/macaroni-os/mark-issues/issues/47 is a requirement for this here?

**Comment by geaaru** [comment]
meh, #47 begin to be a critical issue. leave this in standby for now and eventually add the patch to the tree
