### ISSUE TITLE
sys-apps/fwupd-efi fails regeneration

### ISSUE THREAD

**Issue by org-tekeli-borisp** [macaroni-os/mark-issues#132]
```
INFO     Created: sys-apps/fwupd/fwupd-1.7.7.ebuild                             
INFO     Created: sys-apps/hwloc/hwloc-2.11.1.ebuild                            
INFO     Created: sys-apps/hwinfo/hwinfo-23.2.ebuild                            
ERROR    Autogen failed (count: 1). [<Task finished name='Task-35'              
         coro=<execute_generator.<locals>.generator_thread_task.<locals>.gen_wra
         pper() done, defined at                                                
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/autogen.py:367>
         exception=ValueError('Upstream GitHub asset fwupd-efi-1.7.tar.xz not   
         found.')>]                                                             
ERROR    Errors were encountered when processing the following autogens:        
ERROR     * /home/tree/repo_tmp/source-trees/kit-fixups/generators/github-1.py  
         (sys-apps/fwupd-efi)                                                   
ERROR    End of report.                                                         
[?25h
ERROR    Command failure from merge-kits: cd                                    
         /home/tree/repo_tmp/source-trees/kit-fixups/core-hw-kit/curated && doit
         --fast --release next --fastpull_scope=local --moonbeam --prod         
CRITICAL Step Autogen failed with Exception: failed autogen in                  
         /home/tree/repo_tmp/source-trees/kit-fixups -- offset                  
         core-hw-kit/curated.                                                   
ERROR    Kit job failure:                                                       
         Traceback (most recent call last):                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 678,  
         in run                                                                 
             await method()                                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 470,  
         in generate                                                            
             await self.generate_autogenerated()                                
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 417,  
         in generate_autogenerated                                              
             await self.run(self.autogen_and_copy_from_kit_fixups())            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 159,  
         in run                                                                 
             raise e                                                            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 156,  
         in run                                                                 
             await step.run(self)                                               
           File "/usr/lib/python3.9/site-packages/metatools/steps.py", line 415,
         in run                                                                 
             await self.srctree.autogen(src_offset=self.ebuildloc,              
         scope=self.scope)                                                      
           File "/usr/lib/python3.9/site-packages/metatools/tree.py", line 88,  
         in autogen                                                             
             raise GitTreeError(f"failed autogen in {self.root} -- offset       
         {src_offset}.")                                                        
         metatools.tree.GitTreeError: failed autogen in                         
         /home/tree/repo_tmp/source-trees/kit-fixups -- offset                  
         core-hw-kit/curated.                                                   
[?25h
```

**Comment by org-tekeli-borisp** [comment]
Seems like a new release has happened 2 days ago and assets files are not available yet
https://github.com/fwupd/fwupd-efi/releases
