### ISSUE TITLE
[regen] =gnome-extra/libgsf-1.14.53  fails 

### ISSUE THREAD

**Issue by org-tekeli-borisp** [macaroni-os/mark-issues#142]
```
INFO     Created: media-video/pipewire/pipewire-1.2.5.ebuild                    
ERROR    (metatools.fastpull.spider.FetchRequest<https://download.gnome.org/sour
         ces/libgsf/1.14/libgsf-1.14.53.tar.xz>, 'HTTP fetch_stream Error 404:  
         Not Found')                                                            
INFO     Created: gnome-extra/libgsf/libgsf-1.14.53.ebuild                      
ERROR    (metatools.fastpull.spider.FetchRequest<https://download.gnome.org/sour
         ces/libgsf/1.14/libgsf-1.14.53.tar.xz>, 'HTTP fetch_stream Error 404:  
         Not Found')                                                            
ERROR    Autogen failed (count: 3). [<Task finished name='Task-57'              
         coro=<BreezyBuild.push.<locals>.wrapper() done, defined at             
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:599> 
         exception=https://download.gnome.org/sources/libgsf/1.14/libgsf-1.14.53
         .tar.xz: HTTP fetch_stream Error 404: Not Found>, <Task finished       
         name='Task-57' coro=<BreezyBuild.push.<locals>.wrapper() done, defined 
         at                                                                     
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:599> 
         exception=https://download.gnome.org/sources/libgsf/1.14/libgsf-1.14.53
         .tar.xz: HTTP fetch_stream Error 404: Not Found>, <Task finished       
         name='Task-57' coro=<BreezyBuild.push.<locals>.wrapper() done, defined 
         at                                                                     
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:599> 
         exception=https://download.gnome.org/sources/libgsf/1.14/libgsf-1.14.53
         .tar.xz: HTTP fetch_stream Error 404: Not Found>]                      
ERROR    Errors were encountered when processing the following autogens:        
ERROR     * gnome-extra/libgsf-1.14.53                                          
ERROR    End of report.                                                         
[?25h
ERROR    Command failure from merge-kits: cd                                    
         /home/tree/repo_tmp/source-trees/gnome-kit-sources/ && doit --fast     
         --release next --fastpull_scope=local --moonbeam --prod                
CRITICAL Step Autogen failed with Exception: failed autogen in                  
         /home/tree/repo_tmp/source-trees/gnome-kit-sources -- offset .         
ERROR    Kit job failure:                                                       
         Traceback (most recent call last):                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 678,  
         in run                                                                 
             await method()                                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 472,  
         in generate                                                            
             await self.generate_sourced()                                      
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 387,  
         in generate_sourced                                                    
             await self.run([                                                   
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 159,  
         in run                                                                 
             raise e                                                            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 156,  
         in run                                                                 
             await step.run(self)                                               
           File "/usr/lib/python3.9/site-packages/metatools/steps.py", line 415,
         in run                                                                 
             await self.srctree.autogen(src_offset=self.ebuildloc,              
         scope=self.scope)                                                      
           File "/usr/lib/python3.9/site-packages/metatools/tree.py", line 88,  
         in autogen                                                             
             raise GitTreeError(f"failed autogen in {self.root} -- offset       
         {src_offset}.")                                                        
         metatools.tree.GitTreeError: failed autogen in                         
         /home/tree/repo_tmp/source-trees/gnome-kit-sources -- offset .         
[?25h```

**Comment by org-tekeli-borisp** [comment]
Hmm, strange. Doit locally successed.
``` ╰ $ doit --pkg libgsf
INFO     Cloning/updating kit-fixups to access generators (--fast to use as-is)                                                                                                                                                                                                                                     
INFO     executing: (cd ~/repo_tmp/source-trees/kit-fixups && git pull --ff-only)                                                                                                                                                                                                                        
INFO     Autogen: gnome-extra/libgsf (latest)                                                                                                                                                                                                                                                                       
INFO     Download from https://download.gnome.org/sources/libgsf/1.14/libgsf-1.14.53.tar.xz verified as valid tar.xz archive.                                                                                                                                                                                       
INFO     Created: ../../gnome-extra/libgsf/libgsf-1.14.53.ebuild    ```

**Comment by org-tekeli-borisp** [comment]
Was a temporary problem
