### ISSUE TITLE
[metatools] Permits kit without packages.yaml file

### ISSUE THREAD

**Issue by geaaru** [macaroni-os/mark-issues#148]
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/merge-kits", line 105, in <module>
    if hub.LOOP.run_until_complete(main_thread(args)):
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/lib/python-exec/python3.9/merge-kits", line 67, in main_thread
    success = await controller.generate()
  File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 855, in generate
    success = await self.process_all_kits_in_release(method="generate")
  File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 824, in process_all_kits_in_release
    success = await other_pool.run()
  File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 677, in run
    await kit_job.initialize_sources()
  File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 371, in initialize_sources
    await self.kit.initialize_sources()
  File "/usr/lib/python3.9/site-packages/metatools/release.py", line 258, in initialize_sources
    for repo_name, extra in self.get_kit_items():
  File "/usr/lib/python3.9/site-packages/metatools/release.py", line 303, in get_kit_items
    if section in self.package_data:
  File "/usr/lib/python3.9/site-packages/metatools/release.py", line 246, in package_data
    self._package_data = self._get_package_data()
  File "/usr/lib/python3.9/site-packages/metatools/release.py", line 285, in _get_package_data
    with open(self.packages_yaml, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tree/mark-testing/repo_tmp/source-trees/kit-fixups/xfce-kit/packages.yaml'
```
Considering that our target is avoid using external repo to manage our kit, it could be good to avoid this issue.

**Comment by geaaru** [comment]
Considering the retirement of funtoo-metatools from his creator I prefer follow his wish and implement a new autogen tool better integrate to CDN. I close this issue.
