### ISSUE TITLE
app-editors/vscode-bin fails tree regeneration

### ISSUE THREAD

**Issue by org-tekeli-borisp** [macaroni-os/mark-issues#151]
```
INFO     Created: app-editors/vim-core/vim-core-9.1.0758.ebuild                 
INFO     Created: app-editors/gvim/gvim-9.1.0758.ebuild                         
INFO     Created: app-editors/vim/vim-9.1.0758.ebuild                           
INFO     Created: app-editors/atom-bin/atom-bin-1.60.0.ebuild                   
INFO     Created: app-editors/kakoune/kakoune-2024.05.18.ebuild                 
ERROR    'NoneType' object has no attribute 'split'                             
         Traceback (most recent call last):                                     
           File                                                                 
         "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/autogen.py",  
         line 440, in gen_wrapper                                               
             await generate(AutoHub(autogen_id, pkgtools), **pkginfo)           
           File                                                                 
         "/home/tree/repo_tmp/source-trees/kit-fixups/editors-kit/curated/app-ed
         itors/vscode-bin/autogen.py", line 46, in generate                     
             await generate_for(hub, "code", "stable", True, **pkginfo)         
           File                                                                 
         "/home/tree/repo_tmp/source-trees/kit-fixups/editors-kit/curated/app-ed
         itors/vscode-bin/autogen.py", line 13, in generate_for                 
             deb_filename = redirect_url.split("/")[-1]                         
         AttributeError: 'NoneType' object has no attribute 'split'             
INFO     Created: app-editors/emacs/emacs-29.4.ebuild                           
INFO     Created: app-editors/featherpad/featherpad-1.5.1.ebuild                
INFO     Created: app-editors/nvi/nvi-1.81.6-r8.ebuild                          
INFO     Created: app-editors/amp/amp-0.7.1.ebuild                              
INFO     Created: app-editors/neovim/neovim-0.10.2.ebuild                       
INFO     Created: app-editors/helix/helix-24.07.ebuild                          
INFO     Created: app-editors/micro/micro-2.0.14.ebuild                         
INFO     Created: app-editors/vscodium-bin/vscodium-bin-1.94.0.24281.ebuild     
ERROR    Autogen failed (count: 1). [<Task finished name='Task-19'              
         coro=<execute_generator.<locals>.generator_thread_task.<locals>.gen_wra
         pper() done, defined at                                                
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/autogen.py:371>
         exception=AttributeError("'NoneType' object has no attribute           
         'split'")>]                                                            
ERROR    Errors were encountered when processing the following autogens:        
ERROR     *                                                                     
         /home/tree/repo_tmp/source-trees/kit-fixups/editors-kit/curated/app-edi
         tors/vscode-bin/autogen.py (app-editors/vscode-bin)                    
ERROR    End of report.                                                         
[?25h
ERROR    Command failure from merge-kits: cd                                    
         /home/tree/repo_tmp/source-trees/kit-fixups/editors-kit/curated && doit
         --fast --release next --fastpull_scope=local --moonbeam --prod         
CRITICAL Step Autogen failed with Exception: failed autogen in                  
         /home/tree/repo_tmp/source-trees/kit-fixups -- offset                  
         editors-kit/curated.                                                   
ERROR    Kit job failure:                                                       
         Traceback (most recent call last):                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 680,  
         in run                                                                 
             await method()                                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 470,  
         in generate                                                            
             await self.generate_autogenerated()                                
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 417,  
         in generate_autogenerated                                              
             await self.run(self.autogen_and_copy_from_kit_fixups())            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 159,  
         in run                                                                 
             raise e                                                            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 156,  
         in run                                                                 
             await step.run(self)                                               
           File "/usr/lib/python3.9/site-packages/metatools/steps.py", line 422,
         in run                                                                 
             await self.srctree.autogen(src_offset=self.ebuildloc,              
         scope=self.scope)                                                      
           File "/usr/lib/python3.9/site-packages/metatools/tree.py", line 89,  
         in autogen                                                             
             raise GitTreeError(f"failed autogen in {self.root} -- offset       
         {src_offset}.")                                                        
         metatools.tree.GitTreeError: failed autogen in                         
         /home/tree/repo_tmp/source-trees/kit-fixups -- offset                  
         editors-kit/curated.                                                   
[?25h
```

**Comment by org-tekeli-borisp** [comment]
seems to be a temporal glitch. 
local doit works now 
``` 
╰ $ doit
INFO     Autogen: app-editors/vscode-bin (latest)                                                                                                                                                                                                                                                                   
https://code.visualstudio.com/sha/download?build=stable&os=
INFO     Fetched https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64 (cached, refresh_interval: 0:15:00)                                                                                                                                                                                       
https://vscode.download.prss.microsoft.com/dbazure/download/stable/d78a74bcdfad14d5d3b1b782f87255d802b57511/code_1.94.0-1727878498_amd64.deb
code_1.94.0-1727878498_amd64.deb
INFO     Fetched https://code.visualstudio.com/sha/download?build=stable&os=linux-x64 (cached, refresh_interval: 0:15:00)                                                                                                                                                                                           
https://vscode.download.prss.microsoft.com/dbazure/download/stable/d78a74bcdfad14d5d3b1b782f87255d802b57511/code-stable-x64-1727877074.tar.gz
1.94.0
INFO     Download from https://vscode.download.prss.microsoft.com/dbazure/download/stable/d78a74bcdfad14d5d3b1b782f87255d802b57511/code-stable-x64-1727877074.tar.gz verified as valid tar.gz archive.                                                                                                              
INFO     Created: vscode-bin-1.94.0.ebuild   ```
