### ISSUE TITLE
[python-modules-kit] dev-python/motor doesn't compile

### ISSUE THREAD

**Issue by geaaru** [macaroni-os/mark-issues#182]
```
 * motor-3.6.0.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                                                                         [ ok ]
>>> Unpacking source...
>>> Unpacking motor-3.6.0.tar.gz to /var/tmp/portage/dev-python/motor-3.6.0/work
>>> Source unpacked in /var/tmp/portage/dev-python/motor-3.6.0/work
>>> Preparing source in /var/tmp/portage/dev-python/motor-3.6.0/work/motor-3.6.0 ...
 * Build system packages:
 *   dev-python/gpep517            : 16
 *   dev-python/installer          : 0.5.1-r1
 *   dev-python/hatchling          : 1.25.0
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/motor-3.6.0/work/motor-3.6.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/motor-3.6.0/work/motor-3.6.0 ...
 * python3_9: running distutils-r1_run_phase distutils-r1_python_compile
 *   Building the wheel for motor-3.6.0 via hatchling.build
gpep517 build-wheel --backend hatchling.build --output-fd 3 --wheel-dir /var/tmp/portage/dev-python/motor-3.6.0/work/motor-3.6.0-python3_9/wheel
2024-10-27 09:18:14,058 gpep517 INFO Building wheel via backend hatchling.build
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/gpep517", line 4, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/gpep517/__main__.py", line 439, in main
    return func(args)
  File "/usr/lib/python3.9/site-packages/gpep517/__main__.py", line 229, in build_wheel
    print(build_wheel_impl(args, args.wheel_dir), file=out)
  File "/usr/lib/python3.9/site-packages/gpep517/__main__.py", line 221, in build_wheel_impl
    wheel_name = backend.build_wheel(str(wheel_dir), args.config_json)
  File "/usr/lib/python3.9/site-packages/hatchling/build.py", line 58, in build_wheel
    return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
  File "/usr/lib/python3.9/site-packages/hatchling/builders/plugin/interface.py", line 90, in build
    self.metadata.validate_fields()
  File "/usr/lib/python3.9/site-packages/hatchling/metadata/core.py", line 265, in validate_fields
    _ = self.version
  File "/usr/lib/python3.9/site-packages/hatchling/metadata/core.py", line 149, in version
    self._version = self._get_version()
  File "/usr/lib/python3.9/site-packages/hatchling/metadata/core.py", line 244, in _get_version
    core_metadata = self.core
  File "/usr/lib/python3.9/site-packages/hatchling/metadata/core.py", line 187, in core
    metadata_hooks = self.hatch.metadata.hooks
  File "/usr/lib/python3.9/site-packages/hatchling/metadata/core.py", line 1597, in hooks
    raise UnknownPluginError(message)
hatchling.plugin.exceptions.UnknownPluginError: Unknown metadata hook: requirements_txt
 * ERROR: dev-python/motor-3.6.0::python-modules-kit failed (compile phase):
```

**Comment by geaaru** [comment]
We need `hatch-requirements-txt` to compile
