### ISSUE TITLE
[core-kit] app-admin/ego missing RDEPEND dev-python/mwparserfromhell

### ISSUE THREAD

**Issue by geaaru** [macaroni-os/mark-issues#192]
Running `ego kit` generates an error like this:

```
$> ego kit
ERROR: Ego encountered an unexpected error: ModuleNotFoundError
ERROR: Full traceback written to /tmp/ego-traceback-12808.txt.
```
where the traceback is:
```
$> cat /tmp/ego-traceback-12808.txt 
No module named 'mwparserfromhell'Traceback (most recent call last):
  File "/usr/bin/ego", line 120, in <module>
    EgoModule.run_ego_module(action, econfig, args, VERSION)
  File "/usr/share/ego/python/ego/module.py", line 107, in run_ego_module
    mod = loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/share/ego/modules/kit.ego", line 10, in <module>
    from mediawiki.cli_parser import wikitext_parse
  File "/usr/share/ego/python/mediawiki/cli_parser.py", line 13, in <module>
    import mwparserfromhell
ModuleNotFoundError: No module named 'mwparserfromhell'
```

**Comment by geaaru** [comment]
At the moment `mwparserfromhell` is a PDEPEND. I add at least a post install message for the user.
