### ISSUE TITLE
dev-python/webcolor autogen fails

### ISSUE THREAD

**Issue by org-tekeli-borisp** [macaroni-os/mark-issues#204]
```NFO     Created: dev-python/ruamel-yaml/ruamel-yaml-0.18.6.ebuild              
INFO     Created: dev-python/pyicu/pyicu-2.14.ebuild                            
INFO     Created: dev-python/ruamel-std-pathlib/ruamel-std-pathlib-0.13.0.ebuild
ERROR    Autogen failed (count: 1). [<Task finished name='Task-36'              
         coro=<execute_generator.<locals>.generator_thread_task.<locals>.gen_wra
         pper() done, defined at                                                
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/autogen.py:371>
         exception=ValueError('webcolors: Could not auto-detect build system in 
         pyproject.toml.')>]                                                    
ERROR    Errors were encountered when processing the following autogens:        
ERROR     *                                                                     
         /home/tree/repo_tmp/source-trees/kit-fixups/generators/pypi-compat-1.py
         (dev-python/webcolors)                                                 
ERROR    End of report.                                                         
[?25h
ERROR    Command failure from merge-kits: cd                                    
         /home/tree/repo_tmp/source-trees/kit-fixups/python-modules-kit/next && 
         doit --fast --release next --fastpull_scope=local --moonbeam --prod    
CRITICAL Step Autogen failed with Exception: failed autogen in                  
         /home/tree/repo_tmp/source-trees/kit-fixups -- offset                  
         python-modules-kit/next.                                               
ERROR    Kit job failure:                                                       
         Traceback (most recent call last):                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 680,  
         in run                                                                 
             await method()                                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 470,  
         in generate                                                            
             await self.generate_autogenerated()                                
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 417,  
         in generate_autogenerated                                              
             await self.run(self.autogen_and_copy_from_kit_fixups())            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 159,  
         in run                                                                 
             raise e                                                            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 156,  
         in run                                                                 
             await step.run(self)                                               
           File "/usr/lib/python3.9/site-packages/metatools/steps.py", line 422,
         in run                                                                 
             await self.srctree.autogen(src_offset=self.ebuildloc,              
         scope=self.scope)                                                      
           File "/usr/lib/python3.9/site-packages/metatools/tree.py", line 89,  
         in autogen                                                             
             raise GitTreeError(f"failed autogen in {self.root} -- offset       
         {src_offset}.")                                                        
         metatools.tree.GitTreeError: failed autogen in                         
         /home/tree/repo_tmp/source-trees/kit-fixups -- offset                  
         python-modules-kit/next.                                               
[?25h
```

**Comment by org-tekeli-borisp** [comment]
locally  too
```
 ╰ $ doit --pkg webcolors
WARNING  dict key du_pep517 overwritten.                                                                                                                                                                                                                                                                            
WARNING  dict key du_pep517 overwritten.                                                                                                                                                                                                                                                                            
WARNING  dict key du_pep517 overwritten.                                                                                                                                                                                                                                                                            
INFO     Autogen: dev-python/webcolors (latest)                                                                                                                                                                                                                                                                     
INFO     Download from https://files.pythonhosted.org/packages/7b/29/061ec845fb58521848f3739e466efd8250b4b7b98c1b6c5bf4d40b419b7e/webcolors-24.11.1.tar.gz verified as valid tar.gz archive.                                                                                                                        
ERROR    webcolors: Could not auto-detect build system in pyproject.toml.                                                                                                                                                                                                                                           
         Traceback (most recent call last):                                                                                                                                                                                                                                                                         
           File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/autogen.py", line 436, in gen_wrapper                                                                                                                                                                                                      
             await generate(AutoHub(autogen_id, pkgtools), **pkginfo)                                                                                                                                                                                                                                               
           File "/home/borisp/Development/src/funtoo-infra-core/kit-fixups/generators/pypi-compat-1.py", line 237, in generate                                                                                                                                                                                      
             await add_ebuild(hub, json_dict, compat_ebuild=False, has_compat_ebuild=do_compat_ebuild, **pkginfo)                                                                                                                                                                                                   
           File "/home/borisp/Development/src/funtoo-infra-core/kit-fixups/generators/pypi-compat-1.py", line 205, in add_ebuild                                                                                                                                                                                    
             raise ValueError(f"{local_pkginfo['name']}: Could not auto-detect build system in pyproject.toml.")                                                                                                                                                                                                    
         ValueError: webcolors: Could not auto-detect build system in pyproject.toml.                                                                                                                                                                                                                               
ERROR    Autogen failed (count: 1). [<Task finished name='Task-11' coro=<execute_generator.<locals>.generator_thread_task.<locals>.gen_wrapper() done, defined at /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/autogen.py:367> exception=ValueError('webcolors: Could not auto-detect build system in    
         pyproject.toml.')>]                                                                                                                                                                                                                                                                                        
ERROR    Errors were encountered when processing the following autogens:                                                                                                                                                                                                                                            
ERROR     * ~/kit-fixups/generators/pypi-compat-1.py (dev-python/webcolors)                                                                                                                                                                                            
ERROR    End of report.   ```

**Comment by org-tekeli-borisp** [comment]
https://github.com/ubernostrum/webcolors/blob/trunk/pyproject.toml#L2 
pdm-backend as build-backend?

**Comment by org-tekeli-borisp** [comment]
Seems like **pdm-pep517**  has been renamed a republished as **pdm-backend**
https://pypi.org/project/pdm-pep517/
![image](https://github.com/user-attachments/assets/bdc57e65-edba-40d4-9d15-18152cdc5caa)
https://pypi.org/project/pdm-backend/
