### ISSUE TITLE
[python-modules-kit] `app-misc/yq` does not build

### ISSUE THREAD

**Issue by cuantar** [macaroni-os/mark-issues#21]
```
>>> Compiling source in /var/tmp/portage/app-misc/yq-3.4.3/work/yq-3.4.3 ...
 * python3_9: running distutils-r1_run_phase distutils-r1_python_compile
python3.9 setup.py build -j 24
/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py:55: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
/usr/lib/python3.9/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
Traceback (most recent call last):
  File "/var/tmp/portage/app-misc/yq-3.4.3/work/yq-3.4.3/setup.py", line 5, in <module>
    setup(
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 307, in __init__
    _Distribution.__init__(self, dist_attrs)
  File "/usr/lib/python3.9/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 659, in finalize_options
    ep(self)
  File "/usr/lib/python3.9/site-packages/setuptools_scm/integration.py", line 123, in infer_version
    config = Configuration.from_file(dist_name=dist_name)
  File "/usr/lib/python3.9/site-packages/setuptools_scm/config.py", line 216, in from_file
    return cls(relative_to=name, **args)
TypeError: __init__() got an unexpected keyword argument 'version_file'
```

**Comment by cepelinas9000** [comment]
app-misc/yq have >=setuptools_scm-8.0 dependency - at least at my machine builds. 

@cuantar you can verify using mark-testing with updated setuptools_scm

**Comment by geaaru** [comment]
@cuantar i confirm that moving to `mark-testing` with `setuptools_scm-8` the compilation doesn't fail:
```
# emerge app-misc/yq -j

 * IMPORTANT: 2 config files in '/etc/portage' need updating.
 * See the CONFIGURATION FILES and CONFIGURATION FILES UPDATE TOOLS
 * sections of the emerge man page to learn how to update config files.
Calculating dependencies... done!
>>> Verifying ebuild manifests
>>> Emerging (1 of 7) dev-libs/oniguruma-6.9.9::dev-kit
>>> Emerging (2 of 7) dev-python/argcomplete-3.5.0::python-modules-kit
>>> Emerging (3 of 7) dev-python/xmltodict-0.13.0::python-modules-kit
>>> Emerging (4 of 7) dev-libs/libyaml-0.2.5::core-kit
>>> Installing (3 of 7) dev-python/xmltodict-0.13.0::python-modules-kit
>>> Installing (2 of 7) dev-python/argcomplete-3.5.0::python-modules-kit
>>> Installing (1 of 7) dev-libs/oniguruma-6.9.9::dev-kit
>>> Emerging (5 of 7) app-misc/jq-1.7.1::dev-kit
>>> Installing (4 of 7) dev-libs/libyaml-0.2.5::core-kit
>>> Emerging (6 of 7) dev-python/pyyaml-6.0.2::python-modules-kit
>>> Installing (6 of 7) dev-python/pyyaml-6.0.2::python-modules-kit
>>> Installing (5 of 7) app-misc/jq-1.7.1::dev-kit
>>> Emerging (7 of 7) app-misc/yq-3.4.3::python-modules-kit
>>> Installing (7 of 7) app-misc/yq-3.4.3::python-modules-kit
```
```
 ego profile

=== Enabled Profiles: ===

        arch: x86-64bit
       build: mark
     subarch: generic_64
      flavor: core
     mix-ins: (not set)


=== Python kit: ===

      branch: mark-testing

=== All inherited flavor from core flavor: ===

                         minimal (from core flavor)
```
