### ISSUE TITLE
net-misc/openssh fails the tree regeneration with "Invalid version: '9.8_p1'"

### ISSUE THREAD

**Issue by org-tekeli-borisp** [macaroni-os/mark-issues#214]
```
INFO     Created: app-emulation/docker-cli/docker-cli-24.0.6.ebuild             
INFO     Created: app-emulation/docker-buildx/docker-buildx-0.11.2.ebuild       
INFO     Created: app-emulation/docker-compose/docker-compose-2.21.0.ebuild     
ERROR    Autogen failed (count: 1). [<Task finished name='Task-294'             
         coro=<execute_generator.<locals>.generator_thread_task.<locals>.gen_wra
         pper() done, defined at                                                
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/autogen.py:371>
         exception=InvalidVersion("Invalid version: '9.8_p1'")>]                
ERROR    Errors were encountered when processing the following autogens:        
ERROR     *                                                                     
         /home/tree/mark-testing/repo_tmp/source-trees/kit-fixups/generators/git
         hub-1.py (net-misc/openssh)                                            
ERROR    End of report.                                                         
[?25h
ERROR    Command failure from merge-kits: cd                                    
         /home/tree/mark-testing/repo_tmp/source-trees/kit-fixups/core-kit/curat
         ed && doit --fast --release mark --fastpull_scope=local --moonbeam     
         --prod                                                                 
CRITICAL Step Autogen failed with Exception: failed autogen in                  
         /home/tree/mark-testing/repo_tmp/source-trees/kit-fixups -- offset     
         core-kit/curated.                                                      
ERROR    Kit job failure:                                                       
         Traceback (most recent call last):                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 680,  
     ```

**Comment by org-tekeli-borisp** [comment]
Strange my own tree doesn't have the problem an is on 9.9_p1 already
![image](https://github.com/user-attachments/assets/e2ef1971-4699-4e4a-a209-380c4d57115e)

**Comment by org-tekeli-borisp** [comment]
Oh, why we had pinned to 9,8_p1 in the MARK?
![image](https://github.com/user-attachments/assets/e653c0cb-55c7-4ee1-a03b-591d83e45911)

**Comment by org-tekeli-borisp** [comment]
Ok found why https://github.com/macaroni-os/mark-issues/issues/36#issuecomment-2269709377
Going to remove the pin

**Comment by org-tekeli-borisp** [comment]
Strange local doit fails too after removing of the version pinning
```
 ╰ $ doit
INFO     Autogen: net-misc/openssh (latest)                                                                                                                                                                                                                                                                         
ERROR    Invalid version: '9.9_p1'                                                                                                                                                                                                                                                                                  
         Traceback (most recent call last):                                                                                                                                                                                                                                                                         
           File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/autogen.py", line 436, in gen_wrapper                                                                                                                                                                                                      
             await generate(AutoHub(autogen_id, pkgtools), **pkginfo)                                                                                                                                                                                                                                               
           File "/home/borisp/Development/src/funtoo-infra-core/kit-fixups/generators/github-1.py", line 114, in generate                                                                                                                                                                                           
             github_result = await hub.pkgtools.github.tag_gen(hub, github_user, github_repo, **extra_args)                                                                                                                                                                                                         
           File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/github.py", line 304, in tag_gen                                                                                                                                                                                                           
             result = await latest_tag_version(hub, github_user, github_repo, tag_data=tag_data, transform=transform,                                                                                                                                                                                               
           File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/github.py", line 291, in latest_tag_version                                                                                                                                                                                                
             return max(versions_and_tag_elements, key=lambda v: matcher.sortable(v[0]))                                                                                                                                                                                                                            
           File "/usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/github.py", line 291, in <lambda>                                                                                                                                                                                                          
             return max(versions_and_tag_elements, key=lambda v: matcher.sortable(v[0]))                                                                                                                                                                                                                            
           File "/usr/lib/python3.9/site-packages/metatools/generator/transform.py", line 135, in sortable                                                                                                                                                                                                          
             return packaging.version.parse(version)                                                                                                                                                                                                                                                                
           File "/usr/lib/python3.9/site-packages/packaging/version.py", line 56, in parse                                                                                                                                                                                                                          
             return Version(version)                                                                                                                                                                                                                                                                                
           File "/usr/lib/python3.9/site-packages/packaging/version.py", line 202, in __init__                                                                                                                                                                                                                      
             raise InvalidVersion(f"Invalid version: {version!r}")                                                                                                                                                                                                                                                  
         packaging.version.InvalidVersion: Invalid version: '9.9_p1'                                                                                                                                                                                                                                                
ERROR    Autogen failed (count: 1). [<Task finished name='Task-3' coro=<execute_generator.<locals>.generator_thread_task.<locals>.gen_wrapper() done, defined at /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/autogen.py:367> exception=InvalidVersion("Invalid version: '9.9_p1'")>]                    
ERROR    Errors were encountered when processing the following autogens:                                                                                                                                                                                                                                            
ERROR     * ~/kit-fixups/generators/github-1.py (net-misc/openssh)                                                                                                                                                                                                     
ERROR    End of report.                                                                        ```

**Comment by org-tekeli-borisp** [comment]
@geaaru 
Hmm, could it be related to packaging update from 
https://github.com/macaroni-os/mark-issues/issues/201
https://github.com/macaroni-os/kit-fixups/pull/195  ?

**Comment by org-tekeli-borisp** [comment]
My private tree regenerator is  on the dev-python/packaging-21.3 and it regens the openssh without a problem 
Our public tree regenerator and my local dev machine are already on dev-python/packaging-24.2 and they complain about a invalid version

Private tree regenerator  
```
regen ~ # emerge -pv dev-python/packaging

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] dev-python/packaging-21.3::python-modules-kit  PYTHON_TARGETS="python3_9 -python2_7 -python3_10 -python3_7 -python3_8" 83 KiB

Total: 1 package (1 reinstall), Size of downloads: 83 KiB
``` 
Dev machine
```~ # emerge -av dev-python/packaging

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] dev-python/packaging-24.2::python-modules-kit  PYTHON_TARGETS="python3_9 -python2_7 -python3_10 -python3_7 -python3_8" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No] ```

**Comment by org-tekeli-borisp** [comment]
```
:raises InvalidVersion:
            If the ``version`` does not conform to PEP 440 in any way then this
```
![image](https://github.com/user-attachments/assets/ce161160-0666-4201-8e43-23cbb97c06e7)

**Comment by org-tekeli-borisp** [comment]
https://peps.python.org/pep-0440/

**Comment by org-tekeli-borisp** [comment]
Is patch level **_p1** not conform to PEP 440? Seems like it is

**Comment by geaaru** [comment]
@org-tekeli-borisp yeah, the openssh versioning is not compliant with Gentoo versioning. This the reason why we have a lot of rules on `transform` section of the autogen. It's weird that the pinned version doesn't work anymore. Before upgrade it it's better to investigate why doesn't  work anymore.
This is a critical package, it's been pinned because must be tested before the upgrade.
In addition, I think that could be using the `dirlisting-1` generator too instead of Github optionally.

**Comment by org-tekeli-borisp** [comment]
@geaaru I did an update on regen instance yesterday. So the **dev-python/packaging-24.2** was installed on it. After that the problem has appeared.

**Comment by org-tekeli-borisp** [comment]
Ok, we are switching to static ebuild for net-misc/openssh temporally. In the mean time we will try to find a solution  for version schema incompatibility due to =dev-python/packaging-24.2 PEP 440

**Comment by org-tekeli-borisp** [comment]
Plan change!
@geaaru did a pacth for metatools! ;)
https://github.com/macaroni-os/funtoo-metatools/commit/73e1e797428266fd22b82370bacff799112f2fa3

**Comment by org-tekeli-borisp** [comment]
More fixes ;) https://github.com/macaroni-os/funtoo-metatools/commit/ca9ea8e52620d3f97be6da6ee9a0705911f2884a#diff-17690be89348934d0db162c73875dc897135ce9e721ab9ac71f518463479452dR139

**Comment by geaaru** [comment]
Closing because fixed with https://github.com/macaroni-os/mark-issues/issues/217
