### ISSUE TITLE
[python-modules-kit] dev-python/python-xlib Could not find packaging (compile phase)

### ISSUE THREAD

**Issue by jiggie42** [macaroni-os/mark-issues#220]
this python module is dep of a package I was attempting to install today.  

ERROR: Could not find a version that satisfies the requirement packaging>=20 (from versions: none)
ERROR: No matching distribution found for packaging>=20
Traceback to follow

 * ERROR: dev-python/python-xlib-0.33::python-modules-kit failed (compile phase):

**Comment by jiggie42** [comment]
```
ERROR: Could not find a version that satisfies the requirement packaging>=20 (from versions: none)
ERROR: No matching distribution found for packaging>=20
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
    subprocess.check_call(cmd)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/tmp/portage/dev-python/python-xlib-0.33/temp/tmpx7mexvyd', '--quiet', 'packaging>=20']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/python-xlib-0.33/work/python-xlib-0.33/setup.py", line 12, in <module>
    setup(
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 102, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
    _fetch_build_eggs(dist)
  File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 641, in fetch_build_eggs
    return _fetch_build_eggs(self, requires)
  File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 889, in resolve
    dist = self._resolve_dist(
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 925, in _resolve_dist
    dist = best[req.key] = env.best_match(
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1256, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1292, in obtain
    return installer(requirement) if installer else None
  File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 103, in _fetch_build_egg_no_warn
    raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/usr/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/tmp/portage/dev-python/python-xlib-0.33/temp/tmpx7mexvyd', '--quiet', 'packaging>=20']' returned non-zero exit status 1.
 * ERROR: dev-python/python-xlib-0.33::python-modules-kit failed (compile phase):
 *   (no error message)

```

**Comment by geaaru** [comment]
This is related to the upgrade of `packaging`. I think that this issue could be present in others packages with `standalone` compilation.
We need to update the ebuild with:
```
DISTUTILS_USE_PEP517="setuptools"
```
or with the supported mode.
