### ISSUE TITLE
 =app-misc/meilisearch-1.12.0 fails on autogen and prevents the tree regeneration

### ISSUE THREAD

**Issue by org-tekeli-borisp** [macaroni-os/mark-issues#246]
```
INFO     Created: dev-python/aws-crt-python/aws-crt-python-0.23.6.ebuild        
INFO     Created: app-admin/awscliv2/awscliv2-2.22.23.ebuild                    
ERROR    Autogen failed (count: 1). [<Task finished name='Task-100'             
         coro=<execute_generator.<locals>.generator_thread_task.<locals>.gen_wra
         pper() done, defined at                                                
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/autogen.py:371>
         exception=FileNotFoundError(2, 'No such file or directory')>]          
ERROR    Errors were encountered when processing the following autogens:        
ERROR     *                                                                     
         /home/tree/mark-testing/repo_tmp/source-trees/kit-fixups/core-server-ki
         t/curated/app-misc/meilisearch/autogen.py (app-misc/meilisearch)       
ERROR    End of report.                                                         
[?25h
ERROR    Command failure from merge-kits: cd                                    
         /home/tree/mark-testing/repo_tmp/source-trees/kit-fixups/core-server-ki
         t/curated && doit --fast --release mark --fastpull_scope=local         
         --moonbeam --prod                                                      
CRITICAL Step Autogen failed with Exception: failed autogen in                  
         /home/tree/mark-testing/repo_tmp/source-trees/kit-fixups -- offset     
         core-server-kit/curated.                                               
ERROR    Kit job failure:                                                       
         Traceback (most recent call last):                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 680,  
         in run                                                                 
             await method()                                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 470,  
         in generate                                                            
             await self.generate_autogenerated()                                
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 417,  
         in generate_autogenerated                                              
             await self.run(self.autogen_and_copy_from_kit_fixups())            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 159,  
         in run                                                                 
             raise e                                                            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 156,  
         in run                                                                 
             await step.run(self)                                               
           File "/usr/lib/python3.9/site-packages/metatools/steps.py", line 422,
         in run                                                                 
             await self.srctree.autogen(src_offset=self.ebuildloc,              
         scope=self.scope)                                                      
           File "/usr/lib/python3.9/site-packages/metatools/tree.py", line 89,  
         in autogen                                                             
             raise GitTreeError(f"failed autogen in {self.root} -- offset       
         {src_offset}.")                                                        
         metatools.tree.GitTreeError: failed autogen in                         
         /home/tree/mark-testing/repo_tmp/source-trees/kit-fixups -- offset     
         core-server-kit/curated.                                               
WARNING  The following kits had metadata extraction errors:                     
WARNING  * core-kit branch mark-testing   -- 2 errors.                          
WARNING  metadata extraction errors errors logged to                            
         /home/tree/mark-testing/repo_tmp/tmp.                                  
[?25h
```

**Comment by org-tekeli-borisp** [comment]
Seems like the was a code shifting 
https://github.com/meilisearch/meilisearch/pull/5016/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542
