### ISSUE TITLE
Tree regeneration breaks on net-misc/dropbox/dropbox-206.4.6506.ebuild

### ISSUE THREAD

**Issue by org-tekeli-borisp** [macaroni-os/mark-issues#95]
```
INFO     Created: mail-filter/procmail/procmail-3.24.ebuild                     
ERROR    (metatools.fastpull.spider.FetchRequest<https://edge.dropboxstatic.com/
         dbx-releng/client/dropbox-lnx.x86-206.4.6506.tar.gz>, 'HTTP            
         fetch_stream Error 404: Not Found')                                    
INFO     Created: net-libs/libnet/libnet-1.3.ebuild                             
INFO     Created: net-im/discord-bin/discord-bin-0.0.475.ebuild                 
INFO     Created: net-analyzer/wireshark/wireshark-4.0.10.ebuild                
INFO     Created: net-vpn/tailscale/tailscale-1.72.1.ebuild                     
ERROR    Autogen failed (count: 31). [<Task finished name='Task-662'            
         coro=<BreezyBuild.push.<locals>.wrapper() done, defined at             
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>, <Task  
         finished name='Task-662' coro=<BreezyBuild.push.<locals>.wrapper()     
         done, defined at                                                       
         /usr/lib/python3.9/subpop/org.funtoo.metatools/pkgtools/ebuild.py:600> 
         exception=https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.
         x86-206.4.6506.tar.gz: HTTP fetch_stream Error 404: Not Found>]        
ERROR    Errors were encountered when processing the following autogens:        
ERROR     * net-misc/dropbox-206.4.6506                                         
ERROR    End of report.                                                         
[?25h
ERROR    Command failure from merge-kits: cd                                    
         /home/tree/repo_tmp/source-trees/kit-fixups/net-kit/curated && doit    
         --fast --release next --fastpull_scope=local --moonbeam --prod         
CRITICAL Step Autogen failed with Exception: failed autogen in                  
         /home/tree/repo_tmp/source-trees/kit-fixups -- offset net-kit/curated. 
ERROR    Kit job failure:                                                       
         Traceback (most recent call last):                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 680,  
         in run                                                                 
             await method()                                                     
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 470,  
         in generate                                                            
             await self.generate_autogenerated()                                
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 417,  
         in generate_autogenerated                                              
             await self.run(self.autogen_and_copy_from_kit_fixups())            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 159,  
         in run                                                                 
             raise e                                                            
           File "/usr/lib/python3.9/site-packages/metatools/kit.py", line 156,  
         in run                                                                 
             await step.run(self)                                               
           File "/usr/lib/python3.9/site-packages/metatools/steps.py", line 422,
         in run                                                                 
             await self.srctree.autogen(src_offset=self.ebuildloc,              
         scope=self.scope)                                                      
           File "/usr/lib/python3.9/site-packages/metatools/tree.py", line 89,  
         in autogen                                                             
             raise GitTreeError(f"failed autogen in {self.root} -- offset       
         {src_offset}.")                                                        
         metatools.tree.GitTreeError: failed autogen in                         
         /home/tree/repo_tmp/source-trees/kit-fixups -- offset net-kit/curated. 
[?25h
```

**Comment by org-tekeli-borisp** [comment]
seems like x86 version is not available. I'm not sure if this is temporary. 
```
ERROR    (metatools.fastpull.spider.FetchRequest<https://edge.dropboxstatic.com/dbx-releng/client/dropbox-lnx.x86-206.4.6506.tar.gz>, 'HTTP fetch_stream Error 404: Not Found') 
```

**Comment by geaaru** [comment]
I think that we can just drop x86 version.
